import {Open_Sans} from 'next/font/google'
import './globals.css'
import Header from "./components/Header"
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const openSans = Open_Sans({
  weight: ['400', '800'],
  subsets: ['latin']
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
